---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: influx-grafana
spec:
  ports:
    - port: 3000
      targetPort: grafana-port
      protocol: TCP
  selector:
    app: influx-grafana
  type: LoadBalancer
