---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  labels:
    app: influx-grafana
spec:
  ports:
    - port: 8086
      targetPort: influxdb-port
      protocol: TCP
  selector:
    app: influx-grafana
  type: LoadBalancer
